version: "3.7"

services:
  db:
    container_name: personal-blog-db
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local
